### ISSUE TITLE
This is very sad to see

### ISSUE THREAD

**Issue by abdullah2993** [Black-Hell-Team/G3S#2]

**Comment by xenodesire** [comment]
1st: I never said it was mine

2nd: I just posted it so devs csharp can continue the development

3rd: I talked to the dev by telegram and he authorized her post

And in my opinion to rebuild it even if it is decompiled code! Forgive me if I seem rude and have a good day. ;-)

**Comment by xenodesire** [comment]
> 1st: I never said it was mine
> 
> 2nd: I just posted it so devs csharp can continue the development
> 
> 3rd: I talked to the dev by telegram and he authorized her post
> 
> And in my opinion to rebuild it even if it is decompiled code! Forgive me if I seem rude and have a good day. ;-)

And if you want I can delete the repository

**Comment by abdullah2993** [comment]
Not at all, My issue is not with this being opensource or anything but at least mention it clearly that this is a decompiled version of the original tool(with changes to make it build).
Cheers

**Comment by xenodesire** [comment]
Ok, I'll mention it in the readme
